aws_dbt_snowflake_project:
  outputs:
    dev:
      account: SDWQZYH-PHB73288
      database: AIRBNB
      password: CurlyGypt1234$
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: BRADLEYB30
      warehouse: COMPUTE_WH
  target: dev
